services:
    prometheus:
        image: prom/prometheus:latest
        container_name: engage-plus-prometheus
        restart: always
        ports:
            - "9091:9090"
        volumes:
            - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - --enable-feature=otlp-write-receiver
    grafana:
        image: grafana/grafana:latest
        container_name: engage-plus-grafana
        restart: always
        ports:
            - "3001:3000"
        environment:
            - GF_SERVER_ROOT_URL=http://engage-plus-grafana:3000
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - "./grafana:/etc/grafana/provisioning"
        depends_on:
            - prometheus